### PR TITLE
Rename snapshot conversion functions and add MoBi support

### LINKED ISSUE #1973: Support MoBi projects in loadProjectFromSnapshot()
`loadProjectFromSnapshot()` (introduced when splitting the deprecated `convertSnapshot()`) currently converts **PK-Sim** snapshots (`.json`) into PK-Sim project files (`.pksim5`) only.

Extend it to also load **MoBi** projects from snapshots.

### Tasks
- [ ] Add support for MoBi snapshot -> project conversion
- [ ] Detect/route by project type (PK-Sim vs MoBi)
- [ ] Tests with a MoBi snapshot fixture
- [ ] Update docs (`R/utilities-snapshots.R` Roxygen + snapshots vignette) to drop the "PK-Sim only" caveat once supported

See also the sibling issue for `exportProjectToSnapshot()`.

### LINKED ISSUE #1974: Support MoBi projects in exportProjectToSnapshot()
`exportProjectToSnapshot()` (introduced when splitting the deprecated `convertSnapshot()`) currently converts **PK-Sim** project files (`.pksim5`) into snapshots (`.json`) only.

Extend it to also export **MoBi** projects to snapshots.

### Tasks
- [ ] Add support for MoBi project -> snapshot conversion
- [ ] Detect/route by project type (PK-Sim vs MoBi)
- [ ] Tests with a MoBi project fixture
- [ ] Update docs (`R/utilities-snapshots.R` Roxygen + snapshots vignette) to drop the "PK-Sim only" caveat once supported

See also the sibling issue for `loadProjectFromSnapshot()` (#1973).

### PR DESCRIPTION
**Pull request by Felixmil**
`loadProjectFromSnapshot()` and `exportProjectToSnapshot()` convert files between OSP snapshot JSON and project files. Both had problems: their names promise something they do not do, and they only handled PK-Sim. This renames them to `snapshotToProject()` and `projectToSnapshot()` and teaches them to convert MoBi projects (`.mbp3`) as well, which is the R equivalent of the [`MoBi.CLI snap` workflow](https://docs.open-systems-pharmacology.org/v13/working-with-mobi/mobi-documentation/mobi-command-line-interface#snapshot-workflow-snap).

## Renaming

Neither function returns anything to R; both write files and return `NULL`. `loadProjectFromSnapshot()` therefore reads wrong next to `loadMoBiProject()` (returns a `MoBiProject`) and `loadSimulationsFromSnapshot()` (returns a list of `Simulation`), which really do load into R. Pairing `load*` with `export*` is asymmetric on top of that.

The new names say what happens and in which direction:

| Before | After |
|---|---|
| `loadProjectFromSnapshot()` | `snapshotToProject()` |
| `exportProjectToSnapshot()` | `projectToSnapshot()` |

The old names are removed rather than deprecated. They were introduced in #1975, after the v12.4.3 release, so they have never reached a released version and nobody can be depending on them. `convertSnapshot()`, which *was* released, keeps its `lifecycle` shim and now points at the new names; its `when` is corrected from `"12.4.4"` (a version that was never tagged) to `"13.0.0"`.

## MoBi support

Both functions now accept `.mbp3` projects and MoBi snapshots, and pick the right core automatically:

- **Project to snapshot**: from the file extension.
- **Snapshot to project**: from the snapshot itself. MoBi records `"ApplicationName": "MoBi"` next to `Version` at the top of the file; PK-Sim writes no such field.

A new `application` argument (`"PK-Sim"` or `"MoBi"`) overrides the detection. A single call may mix projects from both applications: the inputs are grouped and each core runs once over its own files, instead of one core silently ignoring the other's files.

No equivalent of the CLI's `--pksim` option was needed. `MoBi.R.Services.PKSimSnapshotConverter` reflects into the `PKSim.R.dll` that sits next to `MoBi.R.dll` in `inst/lib/`, so MoBi snapshots carrying PK-Sim modules convert without a PK-Sim installation.

## .NET plumbing

MoBi exposes no static entry point for this. `MoBi.R.Api` offers only `GetSnapshotTask()`, and the method lives on the instance, so `.runSnapshotConversion()` branches on the application instead of sharing one call. The shared parts (the `cli` progress reporting and the handler that unwraps rSharp's truncated .NET exception text) stay in one place.

The export mode is now passed as a real `SnapshotExportMode` enum object instead of `0L`/`1L`. rSharp will not marshal an R integer into an enum *method parameter*:

```
System.MissingMethodException
Could not find a suitable instance method RunSnapshot on type MoBi.R.Services.SnapshotTask
for method parameters String, String, Boolean, Int32
```

An enum object obtained through `System.Enum.Parse` is accepted both as MoBi's method argument and as PK-Sim's `ExportMode` property, so both cores share one representation and the magic integers are gone.

## Verification

| Check | Result |
|---|---|
| `testthat::test_file("tests/testthat/test-1-utilities-snapshots.R")` | `[ FAIL 0 \| WARN 0 \| SKIP 0 \| PASS 54 ]` |
| `devtools::test()` | `[ FAIL 0 \| WARN 97 \| SKIP 1 \| PASS 2279 ]` |
| `devtools::check(error_on = "never", manual = FALSE)` | `Status: 7 NOTEs`, 0 warnings, 0 errors. All seven pre-existing and unrelated (unit-converter globals, `plotTimeProfile.Rd` line width, source-package and temp-directory notes). |
| Vignette rebuild (inside `check()`) | `checking re-building of vignette outputs ... [226s/186s] OK` |

New tests cover the MoBi round trip (`.mbp3` to `.json` to `.mbp3`, using the existing `tests/data/MoBiProject/Test_Project.mbp3` fixture), application detection for both directions, a mixed batch, the `application` override, and inputs holding no relevant file.

## Notes for the reviewer

- The mixed-batch test copies the MoBi fixture under a different name first. `Test_Project.mbp3` and `test_project.pksim5` both produce `*_project.json`, which collide on a case-insensitive file system.
- MoBi conversion prints the .NET logger's `Information - ...` lines to an interactive console alongside the `cli` progress bar, where PK-Sim prints `0..20..40..`. Cosmetic, and silencing it needs the logger configured on the .NET side, so it is left for a separate change.
- MoBi support in `loadSimulationsFromSnapshot()` and `runSimulationsFromSnapshot()` is out of scope here; their "MoBi snapshots are not yet supported" notes still stand.

## Example

<details><summary>Reprex</summary>

``` r
devtools::load_all("/Users/felix/Code/OSPSuite-R/.claude/worktrees/snapshot-mobi-support-fab453", quiet = TRUE)

moBiProject <- system.file("extdata", "TH_QST_Platform.mbp3", package = "ospsuite")
pkSimSnapshot <- system.file("extdata", "test_snapshot.json", package = "ospsuite")

# A MoBi project converts to a snapshot; the application comes from the extension.
snapshotDir <- withr::local_tempdir()
projectToSnapshot(moBiProject, output = snapshotDir)
#> ℹ Converting 1 MoBi file to snapshot format
#> ✔ Conversion completed
#> 
list.files(snapshotDir)
#> [1] "TH_QST_Platform.json"

# Converting it back detects MoBi from the snapshot itself, no argument needed.
projectDir <- withr::local_tempdir()
snapshotToProject(file.path(snapshotDir, "TH_QST_Platform.json"), output = projectDir)
#> ℹ Converting 1 MoBi file to project format
#> ✔ Conversion completed
#> 
list.files(projectDir)
#> [1] "TH_QST_Platform.mbp3"

# One call may mix applications: each core converts its own files.
mixedDir <- withr::local_tempdir()
snapshotToProject(file.path(snapshotDir, "TH_QST_Platform.json"), pkSimSnapshot, output = mixedDir)
#> ℹ Converting 1 PK-Sim file to project format
#> ✔ Conversion completed
#> 
#> ℹ Converting 1 MoBi file to project format
#> ✔ Conversion completed
#> 
list.files(mixedDir)
#> [1] "test_snapshot.pksim5" "TH_QST_Platform.mbp3"

# `application` overrides the detection.
forcedDir <- withr::local_tempdir()
projectToSnapshot(moBiProject, output = forcedDir, application = "MoBi")
#> ℹ Converting 1 MoBi file to snapshot format
#> ✔ Conversion completed
#> 
list.files(forcedDir)
#> [1] "TH_QST_Platform.json"
```

</details>

Closes #1973
Closes #1974

## Summary by CodeRabbit

* **New Features**
  * Added `projectToSnapshot()` and `snapshotToProject()` for PK-Sim and MoBi project/snapshot conversion.
  * Added automatic application detection, optional overrides, mixed-application batch support, and optional simulation execution.
  * Conversions now reject duplicate filenames and output name collisions instead of overwriting files.

* **Documentation**
  * Updated conversion guidance and examples for PK-Sim and MoBi workflows.

* **Breaking Changes**
  * Replaced `exportProjectToSnapshot()` and `loadProjectFromSnapshot()` with the new conversion functions.

### CODE REVIEW

File: vignettes/snapshots.Rmd [hunk 1]
```diff
@@ -24,8 +24,9 @@ between the snapshot and project formats.
 
 > **Note**
 >
-> The helpers described in this vignette support **PK-Sim snapshots only**;
-> MoBi snapshots are not yet supported.
+> `runSimulationsFromSnapshot()` and `loadSimulationsFromSnapshot()` support
+> **PK-Sim snapshots only**. `snapshotToProject()` and `projectToSnapshot()`
```
Comment (PavelBal) [inline vignettes/snapshots.Rmd:28]: Is this true? Then pls create a new issue to support MoBi projects for this.

**Review by PavelBal — DISMISSED** [review]

File: vignettes/snapshots.Rmd (hunk 1 above)
Comment (Felixmil) [reply vignettes/snapshots.Rmd:28]: Yes, it is true, and I checked both against a real MoBi snapshot rather than assuming. Tracked in #2028.

`loadSimulationsFromSnapshot()` is rejected by PK-Sim's core with an explicit guard:

```
PKSim.Core.PKSimException
This file contains a MoBi project snapshot and cannot be loaded in PK-Sim. Please load it in MoBi.
at PKSim.Core.Snapshots.Services.SnapshotTask.validateApplication(Project snapshot)
```

`runSimulationsFromSnapshot()` is worse: it reports `✔ Simulations completed` and writes an index CSV containing only the `"Sim_id"` header, with no result files. Nothing signals that nothing ran.

The two are not equally easy to fix, which is why #2028 separates them:

- `loadSimulationsFromSnapshot()` can be done now. `LoadSimulationsFromSnapshot` already ships in `inst/lib/MoBi.R.dll`, on the same `ISnapshotTask` interface this PR already uses, and the existing R6 `Simulation` wraps the `MoBiSimulation` objects it returns without changes.
- `runSimulationsFromSnapshot()` is blocked upstream. `MoBi.CLI.Core.dll` has no equivalent of `JsonRunOptions` / `RunJson`, so there is nothing to call until MoBi adds one.

**Comment by Felixmil** [comment]
@PavelBal I stacked this PR on top of your "test files v13 migration" PR (#2031). All tests pass, so this is ready for last review round.

File: NEWS.md [hunk 2]
```diff
@@ -19,6 +19,8 @@ If no original PK-Sim project or snapshot are available, the user should use the
...
 - `DataCombined$toDataFrame()` now returns the `name` and `group` columns as factors whose levels follow the order in which datasets (and groups) were added. As a result, plots built from `DataCombined` objects (`plotTimeProfile()`, `plotPredictedVsObserved()`, `plotResidualsVsCovariate()`, etc.) now display legend entries in the order `DataSet` and `SimulationResults` objects were added, rather than in alphabetical order. This also keeps `name`- and `group`-based legends consistent in observed-vs-predicted plots, where the two variables may otherwise diverge (#1241).
+- `projectToSnapshot()` and `snapshotToProject()` now convert MoBi projects (`.mbp3`) as well as PK-Sim projects (`.pksim5`). The application is detected from the file extension when converting a project and from the snapshot itself when converting a snapshot; the new `application` argument overrides the detection, and a single call may mix projects from both applications. Inputs that would be converted to the same output file, such as `model.pksim5` and `model.mbp3`, are now rejected instead of silently overwriting each other.
```
Comment (PavelBal) [inline NEWS.md]: Drop the "now" wording. This is a new, unreleased functionality, so it was never possible to "silently overwriting each other.". Also the two functions are new.

File: NEWS.md [hunk 3]
```diff
@@ -19,6 +19,8 @@ If no original PK-Sim project or snapshot are available, the user should use the
...
+- `runSimulationsFromSnapshot()`, `projectToSnapshot()` and `snapshotToProject()` now raise an error when two input files share a name, for example `snapshots/a/model.json` and `snapshots/b/model.json`. All inputs are gathered into a single folder before conversion, so previously the second file replaced the first and was silently processed in its place.
```
Comment (PavelBal) [inline NEWS.md]: Same here.

Also in general, write this as "new functions projectToSnapshot and snapshotToProject"

**Review by PavelBal — CHANGES_REQUESTED** [review]
Two comments on the NEWS file

File: vignettes/snapshots.Rmd (hunk 1 above)
Comment (Felixmil) [reply vignettes/snapshots.Rmd:28]: Yes, it is true. Both `loadSimulationsFromSnapshot()` and `runSimulationsFromSnapshot()` route through `PKSim.R.Api`, so a MoBi snapshot cannot be used with either. MoBi support for them is tracked in #2028, which also records that `runSimulationsFromSnapshot()` fails silently on a MoBi snapshot.

File: NEWS.md (hunk 2 above)
[the remark this answers is not in the document]
Comment (Felixmil) [reply NEWS.md]: Done in 9b664a07c. The bullet now states each direction separately: `projectToSnapshot()` takes `.pksim5` and `.mbp3` project files and writes `.json` snapshots, `snapshotToProject()` takes PK-Sim and MoBi `.json` snapshots and writes the matching `.pksim5` or `.mbp3` project file. The detection, override, mixed-batch, and collision details are kept.

Comment (Felixmil) [reply NEWS.md]: Done in 9b664a07c. The bullet now opens with "New functions `projectToSnapshot()` and `snapshotToProject()`" and states both rejection rules in the present tense, with no "now", no "previously", and no "silently overwriting each other".

File: NEWS.md (hunk 3 above)
Comment (Felixmil) [reply NEWS.md]: Done in 9b664a07c. The two new functions are out of this bullet, their share of the statement moved into the "New functions ..." bullet above. This bullet now covers `runSimulationsFromSnapshot()` only, which shipped in 12.2.0, so for it the "now raises an error / previously" framing describes a real behavior change and is kept.

**Review by PavelBal — APPROVED** [review]
