### ISSUE TITLE
ContainerType should return string instead of number

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#109]
@PavelBal I think you are right. It won't be very useful otherwise. Better to have the overhead

**Comment by msevestre** [comment]
And the ContainerType is not available outside of the package. Weird, I was pretty sure it worked. Probably it was cached in my session

@PavelBal How to export an enum such as `ContainerType` so that it is available outside of the package as readonly?

**Comment by PavelBal** [comment]
I don't think you caan make something read-only...

But why do you want to have it available outside of the package? In fact, can't the public funciton `$containerType` always return the string representation of the type? I can't think of an example where the user would need the integer....

**Comment by PavelBal** [comment]
Well OK, I actually can think of use-cases...

Then we could just export the function `containerType` (and maybe rename it to `getContainerTypes`). So the user can get containers, use the numeric representation of `ContainerType` e.g. for some decisions, and use the list returned by `getContainerTypes()` to see what is what..

**Comment by msevestre** [comment]
No I want to export the enum so that the user can have autocompletion outside of the package

E.g. containerType$Organism so that you don't have to wrtie "Organism" all the time

How can I expose the list in short? Nevermind readonly

**Comment by PavelBal** [comment]
Use
`ContainerType <<- containerType()` instead of `ContainerType <- containerType()` in `zzz.R`.

**Comment by msevestre** [comment]
But this is going to pollute the global namespace and that's bad practice.

There has to be a way to export a variable that is not a function in a package in a namespace no?

What's the use case for using number for container type? This is purely internal

**Comment by PavelBal** [comment]
> What's the use case for using number for container type? This is purely internal

E.g. return all containers and filter for reactions.... But this is not so important, I think.
But in this case, again - what would be the use case for having the enum outside of the package?

**Comment by msevestre** [comment]
> return all containers and filter for reactions..

This is a valid use case. Tht;ats why I want to export the enum. I wnat the user to be able to filter
using containerType$reaction rather than 5 (or whatever number that is)

e.g. this enumeration needs to be available outside of the package

**Comment by PavelBal** [comment]
Well, the easiest (and honestly the only I found) way would be:

Remove 
```
  #' ContainerType <- containerType()

  # # Ensures that the variable ContainerType is available in the package as ospsuite::ContainerType
  # assign("ContainerType", ContainerType, envir = parent.env(environment()))
```

from `zzz.R`. Instead, define `containerType.R` as

```
#' @export
ContainerType <- list(
    Other = 0,
    Simulation = 1,
    Model = 2,
    Organism = 3,
    Organ = 4,
    Compartment = 5,
    Application = 6,
    Event = 7,
    EventGroup = 8,
    Neighborhood = 9,
    Molecule = 10,
    Reaction = 11,
    Formulation = 12,
    Transport = 13
  )

```

**Comment by msevestre** [comment]
If I am trying to do

```

getContainerType <- function() {
  enum(c(
    Other = 0,
    Simulation = 1,
    Model = 2,
    Organism = 3,
    Organ = 4,
    Compartment = 5,
    Application = 6,
    Event = 7,
    EventGroup = 8,
    Neighborhood = 9,
    Molecule = 10,
    Reaction = 11,
    Formulation = 12,
    Transport = 13
  ))
}


#' @export
ContainerType <- getContainerType()
```

I get the error that the enum method is not defined. I just don't get it. I like this enum wrapper because you can define enum without values such as `enum(c(LIN, LOG))` etc.

What a pain

**Comment by msevestre** [comment]
```
 Error in enum(c(Other = 0, Simulation = 1, Model = 2, Organism = 3, Organ = 4,  (from container-type.R#3) : 
  could not find function "enum" 
```

do you know why it's like that?

**Comment by PavelBal** [comment]
No, I also tried to export it es `enum()` and got the error.

But in this particular case, if you export `ContainerType` as a list bypassing `enum`, the results are the same, right? Because at the end enum also just returns a list...

**Comment by msevestre** [comment]
correct. However it would be nice to be able to use the helper function somehow (which creates values for you automatically so that you don't have to assign values if you don't need to)
I just don't understand WHY it does not work

**Comment by msevestre** [comment]
so it works if I use `ospsuite:::ContainerType$Simulation` instead of `::` 

What's the difference between :: and ::: ??~~??~?

**Comment by msevestre** [comment]
https://stat.ethz.ch/R-manual/R-devel/library/base/html/ns-dblcolon.html
not good practice to use :::

ok then. Maybe we'll go with a list if we cannot understand why it's not possible to assign a variable using enum

**Comment by PavelBal** [comment]
> I just don't understand WHY it does not work

The more I read about R, the less I understand :D

**Comment by msevestre** [comment]
Ok I have updated the code to use a list instead
I have kept the enum helper in for now

**Comment by msevestre** [comment]
Should we keep the numbers for now then?

**Comment by PavelBal** [comment]
Yes, keep the numbers and add to the documentation where to find the assignments of numbers to strings (`ospsuite::ContainerType`).

`print()` should show the container type as string.

**Comment by PavelBal** [comment]
@msevestre We agreed on returning the int value, but now there is no direct way to see what is the string representation of this type...

Maybe the `Container` class should have two properties - `containerTypeInt` and `containerTypeStr`? Additionally, the `print()` override should be implemented for `Container`.

**Comment by PavelBal** [comment]
See PR https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/132

**Comment by PavelBal** [comment]
Closed via #132
